### ISSUE TITLE
[ NPM Build ] Getting Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script

### ISSUE THREAD

**Issue by punithbm** [robot-ux/wallet-core-example#4]
When trying to use the wallet-core with [viteJs](https://vitejs.dev/), it works fine in the development environment.
But after build, we are getting uncaught eval error due to unsafe-eval as shown below:

![Screenshot 2022-07-29 at 11 18 43 PM](https://user-images.githubusercontent.com/13044958/181817599-4bc9ba9b-1976-4a66-ac80-1011a7e9edaf.png)

I have already raised an issue here in the trust wallet. https://github.com/trustwallet/wallet-core/issues/2429
Please let me know if you know of any workaround for this error.

**Comment by robot-ux** [comment]
fixed by https://github.com/trustwallet/wallet-core/issues/2429
